web:
  host: mail.vsendv.com 
  protocol: https

fast_server:
  enabled: true
  bind_address: 138.68.192.134
  port: 5010
  ssl_port: 5011

general:
  use_ip_pools: false

main_db:
  host: 127.0.0.1
  username: root
  password:
  database: postal_test

message_db:
  host: 127.0.0.1
  username: root
  password:
  prefix: postal_test

rabbitmq:
  host: 127.0.0.1
  username: guest
  password: guest
  vhost:

smtp_server:
  port: 2525

dns: 
  mx_records:
    - mx.mail.vsendv.com
  smtp_server_hostname: mail.vsendv.com
  spf_include: spf.mail.vsendv.com
  return_path: rp.mail.vsendv.com
  route_domain: routes.mail.vsendv.com
  track_domain: track.mail.vsendv.com

rails:
  environment: test
  secret_key: c3ed0d4723a5d08f8cdb03571ddec8366da74db114f5419187343632e9c0c0110da177c0cf79e6605a4ccfff6f2d9e716d99b6525401ad9c181466b57a1901ffeacb023d05c9ce69838dd826f54e29c846e9e3231697c6749648a9c706df20b50bec1d7ef81b0dbd91410b314c44a4c0cf74741df2de9f5bb144026a6f99954c
